# Created using wingetcreate 1.1.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json

PackageIdentifier: WarcraftLogs.Uploader
PackageVersion: 5.9.5.162
PackageLocale: en-US
Publisher: Warcraft Logs
PackageName: Warcraft Logs Uploader
License: GNU General Public License
Copyright: Copyright © 2022 warcraftlogs
ShortDescription: Allows the upload of World of Warcraft log files for analysis at WarcraftLogs.com
ManifestType: defaultLocale
ManifestVersion: 1.2.0

